const ABILITY_DESCRIPTIONS_PT_BR: Record<string, string> = {
	blaze: 'Quando o Pokémon está com 1/3 ou menos do HP máximo, o poder de seus golpes do tipo Fire é multiplicado por 1,5.',
	chlorophyll: 'Sob sol forte, a Speed deste Pokémon é multiplicada por 2.',
	drizzle: 'Ao entrar em campo, o Pokémon inicia chuva por 5 turnos.',
	drought: 'Ao entrar em campo, o Pokémon inicia sol forte por 5 turnos.',
	flamebody: 'Golpes de contato contra este Pokémon possuem 30% de chance de causar Burn no atacante.',
	guts: 'Quando o Pokémon possui um status principal, seu Attack é multiplicado por 1,5 e Burn não reduz seu Attack.',
	hugepower: 'O valor de Attack deste Pokémon é multiplicado por 2.',
	innerfocus: 'O Pokémon não pode sofrer flinch e é imune à redução de Attack causada por Intimidate.',
	intimidate: 'Ao entrar em campo, reduz o Attack dos oponentes adjacentes em 1 estágio.',
	keeneye: 'A Accuracy deste Pokémon não pode ser reduzida por outros Pokémon. Também ignora aumentos de Evasion do alvo.',
	levitate: 'O Pokémon é imune a golpes do tipo Ground e a determinados efeitos que atingem Pokémon no chão.',
	magicguard: 'O Pokémon sofre dano apenas de ataques diretos.',
	moxie: 'Quando este Pokémon faz outro Pokémon desmaiar com um ataque, seu Attack aumenta em 1 estágio.',
	multiscale: 'Quando está com o HP cheio, o dano sofrido por este Pokémon é reduzido pela metade.',
	naturalcure: 'O status principal deste Pokémon é removido quando ele deixa o campo de batalha.',
	overgrow: 'Quando o Pokémon está com 1/3 ou menos do HP máximo, o poder de seus golpes do tipo Grass é multiplicado por 1,5.',
	poisonpoint: 'Golpes de contato contra este Pokémon possuem 30% de chance de causar Poison no atacante.',
	prankster: 'Os golpes da categoria Status usados por este Pokémon recebem prioridade +1. Golpes afetados não funcionam contra Pokémon do tipo Dark.',
	pressure: 'O oponente perde 1 PP adicional ao usar um golpe que tenha este Pokémon como alvo.',
	regenerator: 'O Pokémon recupera 1/3 do HP máximo quando deixa o campo de batalha.',
	sandstream: 'Ao entrar em campo, o Pokémon inicia Sandstorm por 5 turnos.',
	snowwarning: 'Ao entrar em campo, o Pokémon inicia Snow por 5 turnos.',
	static: 'Golpes de contato contra este Pokémon possuem 30% de chance de causar Paralysis no atacante.',
	sturdy: 'Com o HP cheio, o Pokémon não pode ser derrotado por um único golpe e permanece com 1 HP. Também é imune a golpes de nocaute instantâneo.',
	swiftswim: 'Durante a chuva, a Speed deste Pokémon é multiplicada por 2.',
	synchronize: 'Quando outro Pokémon causa Burn, Paralysis ou Poison neste Pokémon, o mesmo status também é aplicado ao causador, quando possível.',
	technician: 'O poder dos golpes com poder base de 60 ou menos é multiplicado por 1,5.',
	thickfat: 'O dano recebido de golpes dos tipos Fire e Ice é reduzido pela metade.',
	torrent: 'Quando o Pokémon está com 1/3 ou menos do HP máximo, o poder de seus golpes do tipo Water é multiplicado por 1,5.',
	trace: 'Ao entrar em campo, o Pokémon copia uma habilidade válida de um oponente aleatório.',
	waterabsorb: 'O Pokémon é imune a golpes do tipo Water e recupera 1/4 do HP máximo quando é atingido por um deles.',
	solarpower: 'Sob sol forte, o Sp. Attack deste Pokémon é multiplicado por 1,5, mas ele perde 1/8 do HP máximo ao final de cada turno.',
	plus: 'O Sp. Attack deste Pokémon é multiplicado por 1,5 enquanto um aliado em campo possuir Plus ou Minus.',
	sapsipper: 'O Pokémon é imune a golpes do tipo Grass. Quando é atingido por um deles, seu Attack aumenta em 1 estágio.',
	healer: 'Ao final de cada turno, há 30% de chance de curar o status principal de cada aliado adjacente.',
	flashfire: 'O Pokémon é imune a golpes do tipo Fire. Após ser atingido por um deles, o poder de seus próprios golpes Fire é multiplicado por 1,5 enquanto permanecer em campo.',
	leafguard: 'Sob sol forte, o Pokémon não pode receber condições principais de status.',
	infiltrator: 'Os golpes deste Pokémon ignoram Substitute, Reflect, Light Screen, Aurora Veil, Safeguard e Mist do alvo.',
	damp: 'Impede o uso de golpes que fazem o usuário explodir e também impede a ativação de Aftermath.',
	telepathy: 'O Pokémon é imune a golpes que causam dano usados por seus aliados.',
	raindish: 'Durante a chuva, o Pokémon recupera 1/16 do HP máximo ao final de cada turno.',
	rockhead: 'O Pokémon não sofre dano de recuo causado por seus próprios golpes.',
	rattled: 'Quando o Pokémon é atingido por um golpe Bug, Dark ou Ghost, ou sofre Intimidate, sua Speed aumenta em 1 estágio.',
};

const GENERATED_ABILITY_DESCRIPTIONS_PT_BR: Record<string, string> = {
	"adaptability": "O bônus de ataque do mesmo tipo (STAB) deste Pokémon é 2 em vez de 1,5.",
	"aerilate": "Os golpes do tipo Normal deste Pokémon tornam-se do tipo Flying e têm 1,2x de poder.",
	"aftermath": "Se este Pokémon for desmaiado com um golpe de contato, o usuário desse golpe perde 1/4 do seu HP máximo.",
	"airlock": "Enquanto este Pokémon estiver ativo, os efeitos das condições climáticas estarão desativados.",
	"analytic": "Os ataques deste Pokémon têm 1,3x de poder se ele for o último a se mover no turno.",
	"angerpoint": "Se este Pokémon (não seu substituto) sofrer um golpe crítico, seu Attack aumentará 12 estágios.",
	"angershell": "Com 1/2 ou menos do HP máximo deste Pokémon: +1 Atk, Sp. Attack, Spe e -1 Def, Sp. Defense.",
	"anticipation": "Ao entrar em campo, este Pokémon estremece se algum oponente tiver um move super effective ou OHKO.",
	"arenatrap": "Impede que Pokémon adversários optem por trocar, a menos que estejam no ar.",
	"armortail": "Este Pokémon e seus aliados estão protegidos de golpes com prioridade adversários.",
	"aromaveil": "Protege usuários/aliados de Atrair, Desabilitar, Encore, Bloqueio de Cura, Provocação e Tormento.",
	"asoneglastrier": "Combinação das habilidades Unnerve e Chilling Neigh.",
	"asonespectrier": "Combinação das habilidades Unnerve e Grim Neigh.",
	"aurabreak": "Enquanto este Pokémon estiver ativo, o modificador de poder Dark Aura e Fairy Aura é de 0,75x.",
	"baddreams": "Faz com que os oponentes com Sleep percam 1/8 do seu HP máximo no final de cada turno.",
	"ballfetch": "Não produz efeito durante a batalha.",
	"battery": "Os aliados deste Pokémon têm o poder de seus ataques especiais multiplicado por 1,3.",
	"battlearmor": "Este Pokémon não pode ser atingido por um golpe crítico.",
	"battlebond": "Depois de fazer desmaiar um Pokémon: aumenta Attack, Sp. Attack, Speed em 1 estágio. Uma vez por batalha.",
	"beadsofruin": "Pokémon ativos sem esta habilidade têm sua Sp. Defense multiplicada por 0,75.",
	"beastboost": "A estatística mais alta deste Pokémon aumenta em 1 se ele atacar e fazer desmaiar outro Pokémon.",
	"berserk": "O Sp. Attack deste Pokémon aumenta em 1 quando atinge 1/2 ou menos de seu HP máximo.",
	"bigpecks": "Impede que outros Pokémon reduzam o estágio de atributo de Defense deste Pokémon.",
	"blaze": "Com 1/3 ou menos de seu HP máximo, a estatística ofensiva deste Pokémon é 1,5x com golpes Fire.",
	"bulletproof": "Este Pokémon é imune a golpes de bala.",
	"cheekpouch": "Se este Pokémon comer uma Berry, ele restaura 1/3 do seu HP máximo após o efeito da Berry.",
	"chillingneigh": "O ataque deste Pokémon aumenta em 1 estágio se ele atacar e fazer desmaiar outro Pokémon.",
	"chlorophyll": "Se Sunny Day estiver ativo, a Speed deste Pokémon será duplicada.",
	"clearbody": "Impede que outros Pokémon reduzam os estágios de atributos deste Pokémon.",
	"cloudnine": "Enquanto este Pokémon estiver ativo, os efeitos das condições climáticas estarão desativados.",
	"colorchange": "O tipo deste Pokémon muda de acordo com o tipo de golpe que ele atinge, a menos que ele tenha o tipo.",
	"comatose": "Este Pokémon não pode ser status e é considerado com Sleep.",
	"commander": "Se o aliado for Dondozo: este Pokémon não pode agir ou ser atingido, +2 para todas as estatísticas de Dondozo.",
	"competitive": "O Sp. Attack deste Pokémon é aumentado em 2 para cada uma de suas estatísticas reduzida por um oponente.",
	"compoundeyes": "Os golpes deste Pokémon têm sua Accuracy multiplicada por 1,3.",
	"contrary": "Se este Pokémon tiver um estágio de atributo aumentado, ele será reduzido e vice-versa.",
	"corrosion": "Este Pokémon pode envenenar ou envenenar gravemente um Pokémon, independentemente de seu tipo.",
	"costar": "Ao entrar em campo, este Pokémon copia todas as mudanças de status de seu aliado.",
	"cottondown": "Se este Pokémon for atingido, a Speed de todos os outros Pokémon no campo será reduzida em 1 estágio.",
	"cudchew": "Se este Pokémon comer uma Berry, ele a comerá novamente no final do próximo turno.",
	"curiousmedicine": "Ao entrar em campo, os aliados deste Pokémon têm seus estágios de atributos redefinidos para 0.",
	"cursedbody": "Se este Pokémon for atingido por um ataque, há 30% de chance de que o golpe seja desativado.",
	"cutecharm": "30% de chance de apaixonar Pokémon do sexo oposto se eles fizerem contato.",
	"damp": "Previne Explosão/Mind Blown/Mind Explosion/Autodestruição/Consequências enquanto ativo.",
	"dancer": "Depois que outro Pokémon usa um golpe de dança, este Pokémon usa o mesmo golpe.",
	"darkaura": "Enquanto este Pokémon estiver ativo, um golpe Dark usado por qualquer Pokémon terá 1,33x de poder.",
	"dauntlessshield": "Ao entrar em campo, a defesa deste Pokémon aumenta em 1 estágio. Uma vez por batalha.",
	"dazzling": "Este Pokémon e seus aliados estão protegidos de golpes com prioridade adversários.",
	"defeatist": "Embora este Pokémon tenha 1/2 ou menos de seu HP máximo, seu Ataque e Sp. Attack é reduzido pela metade.",
	"defiant": "O ataque deste Pokémon é aumentado em 2 para cada uma de suas estatísticas reduzidas por um oponente.",
	"deltastream": "Ao entrar em campo, ventos fortes começam até que esta habilidade não esteja ativa na batalha.",
	"desolateland": "Ao entrar em campo, a luz solar extremamente forte começa até que esta habilidade não esteja ativa na batalha.",
	"disguise": "(Somente Mimikyu) O primeiro golpe recebido é bloqueado e, em vez disso, sofre 1/8 de dano de HP.",
	"download": "Ao entrar em campo, Attack ou Sp. Attack aumenta 1 estágio com base na Defense mais fraca do oponente.",
	"dragonsmaw": "A estatística ofensiva deste Pokémon é multiplicada por 1,5 ao usar um ataque do tipo Dragon.",
	"drizzle": "Ao entrar em campo, este Pokémon invoca Rain Dance.",
	"drought": "Ao entrar em campo, este Pokémon invoca Sunny Day.",
	"dryskin": "Este Pokémon é curado 1/4 por Water, 1/8 pela chuva; é ferido 1,25x por Fire, 1/8 pelo Sol.",
	"earlybird": "O contador de Sleep deste Pokémon cai 2 em vez de 1.",
	"eartheater": "Este Pokémon cura 1/4 do seu HP máximo quando atingido por golpes Ground; Imunidade a Ground.",
	"effectspore": "30% de chance de Poison/Paralysis/Sleep em outras pessoas que fizerem contato com este Pokémon.",
	"electricsurge": "Ao entrar em campo, este Pokémon invoca Electric Terrain.",
	"electromorphosis": "Este Pokémon ganha o efeito Charge quando é atingido por um ataque.",
	"embodyaspectcornerstone": "Ao entrar em campo, a defesa deste Pokémon aumenta em 1 estágio.",
	"embodyaspecthearthflame": "Ao entrar em campo, o ataque deste Pokémon aumenta em 1 estágio.",
	"embodyaspectteal": "Ao entrar em campo, a Speed deste Pokémon aumenta em 1 estágio.",
	"embodyaspectwellspring": "Ao entrar em campo, a Sp. Defense deste Pokémon aumenta em 1 estágio.",
	"emergencyexit": "Este Pokémon troca quando atinge 1/2 ou menos do seu HP máximo.",
	"fairyaura": "Enquanto este Pokémon estiver ativo, um golpe Fairy usado por qualquer Pokémon terá 1,33x de poder.",
	"filter": "Este Pokémon recebe 3/4 do dano de ataques super effective.",
	"flamebody": "30% de chance de um Pokémon que fizer contato com este Pokémon receber Burn.",
	"flareboost": "Enquanto este Pokémon estiver com Burn, seus ataques especiais terão 1,5x de poder.",
	"flashfire": "Os golpes Fire deste Pokémon causam 1,5x de dano se forem atingidos por um golpe de Fogo; Imunidade a Fire.",
	"flowergift": "Se o usuário for Cherrim e Sunny Day estiver ativo, ele e os aliados Attack e Sp. Defense são 1,5x.",
	"flowerveil": "Os tipos Grass deste lado não podem ter estatísticas reduzidas ou status infligidos por outros Pokémon.",
	"fluffy": "Este Pokémon sofre 1/2 do dano dos golpes de contato e 2x do dano dos golpes Fire.",
	"forecast": "O tipo do Castform muda para o tipo da condição climática atual, exceto Sandstorm.",
	"forewarn": "Ao entrar em campo, este Pokémon é alertado sobre o golpe do oponente com maior poder.",
	"friendguard": "Os aliados deste Pokémon recebem 3/4 do dano dos ataques de outros Pokémon.",
	"frisk": "Ao entrar em campo, este Pokémon identifica os itens equipados de todos os Pokémon adversários.",
	"fullmetalbody": "Impede que outros Pokémon reduzam os estágios de atributos deste Pokémon.",
	"furcoat": "A defesa deste Pokémon é duplicada.",
	"galewings": "Se este Pokémon estiver com HP máximo, seus golpes do tipo Flying terão sua prioridade aumentada em 1.",
	"galvanize": "Os golpes do tipo Normal deste Pokémon tornam-se do tipo Electric e têm 1,2x de poder.",
	"gluttony": "Este Pokémon come Berries com 1/2 HP máximo ou menos, em vez de 1/4 do HP máximo normal.",
	"goodasgold": "Este Pokémon é imune a golpes da categoria Status.",
	"gooey": "Pokémon que fazem contato com este Pokémon têm sua Speed reduzida em 1 estágio.",
	"gorillatactics": "O ataque deste Pokémon é 1,5x, mas ele só pode selecionar o primeiro golpe que executa.",
	"grasspelt": "Se Grassy Terrain estiver ativo, a defesa deste Pokémon será multiplicada por 1,5.",
	"grassysurge": "Ao entrar em campo, este Pokémon invoca Grassy Terrain.",
	"grimneigh": "O Sp. Attack deste Pokémon aumenta em 1 estágio se atacar e fazer desmaiar outro Pokémon.",
	"guarddog": "Imune à intimidação. Intimidado: +1 Ataque. Não pode ser forçado a mudar.",
	"gulpmissile": "Quando atingido após Surf/Dive, o atacante recebe 1/4 do HP máximo e -1 de Defesa ou Paralysis.",
	"guts": "Se este Pokémon estiver com status, seu ataque será 1,5x; ignora a Burn, reduzindo pela metade o dano físico.",
	"hadronengine": "Ao entrar em campo, invoca Electric Terrain. Durante Electric Terrain, Sp. Attack é 1,3333x.",
	"harvest": "Se o último item usado for uma Berry, 50% de chance de restaurá-la a cada final de turno. 100% ao sol.",
	"healer": "30% de chance do aliado deste Pokémon ter seu status curado ao final de cada turno.",
	"heatproof": "O dano de fogo contra este Pokémon é causado com 1/2 estatística ofensiva; 1/2 dano de Burn.",
	"heavymetal": "O peso deste Pokémon é duplicado.",
	"honeygather": "Não produz efeito durante a batalha.",
	"hospitality": "Ao entrar em campo, este Pokémon restaura 1/4 do HP máximo de seu aliado, arredondado para baixo.",
	"hugepower": "O ataque deste Pokémon é duplicado.",
	"hungerswitch": "Se for Morpeko, ele muda entre Full Belly e Hangry Mode no final de cada turno.",
	"hustle": "O ataque deste Pokémon é de 1,5x e a Accuracy de seus ataques físicos é de 0,8x.",
	"hydration": "Este Pokémon tem seu status curado no final de cada turno se Rain Dance estiver ativo.",
	"hypercutter": "Impede que outros Pokémon reduzam o estágio de atributo de ataque deste Pokémon.",
	"icebody": "Se Snow estiver ativo, este Pokémon cura 1/16 de seu HP máximo a cada turno.",
	"iceface": "Se for Eiscue, o primeiro golpe físico causado causa 0 de dano. O efeito é restaurado durante Snow.",
	"icescales": "Este Pokémon recebe 1/2 do dano de ataques especiais.",
	"illuminate": "A Accuracy deste Pokémon não pode ser reduzida por outros; ignora sua estatística de evasão.",
	"illusion": "Este Pokémon aparece como o último Pokémon do grupo até sofrer dano direto.",
	"immunity": "Este Pokémon não pode ser com Poison. Ganhar esta habilidade enquanto estiver com Poison a cura.",
	"imposter": "Ao entrar em campo, este Pokémon se transforma no Pokémon oponente que o enfrenta.",
	"infiltrator": "Golpes ignoram substitutos e Reflect/Light Screen/Safeguard/Mist/Aurora Veil do oponente.",
	"innardsout": "Se este Pokémon for desmaiado com um golpe, o usuário desse golpe perde uma quantidade igual de HP.",
	"innerfocus": "Este Pokémon não pode recuar. Imune à intimidação.",
	"insomnia": "Este Pokémon não consegue dormir. Ganhar esta habilidade enquanto dorme cura-a.",
	"intimidate": "Ao entrar em campo, este Pokémon reduz o ataque dos oponentes em 1 estágio.",
	"intrepidsword": "Ao entrar em campo, o ataque deste Pokémon aumenta em 1 estágio. Uma vez por batalha.",
	"ironbarbs": "Pokémon que fazem contato com este Pokémon perdem 1/8 de seu HP máximo.",
	"ironfist": "Os ataques baseados em socos deste Pokémon têm poder de 1,2x. Sucker Punch não é aumentado.",
	"justified": "O ataque deste Pokémon aumenta em 1 estágio após ser danificado por um golpe do tipo Dark.",
	"keeneye": "A Accuracy deste Pokémon não pode ser reduzida por outros; ignora sua estatística de evasão.",
	"klutz": "O item segurado deste Pokémon não tem efeito, exceto Macho Brace. Fling não pode ser usado.",
	"leafguard": "Se Sunny Day estiver ativo, este Pokémon não poderá ser status e Rest falhará por isso.",
	"levitate": "Este Pokémon é imune ao Ground; Gravidade/Ingrain/Smack Down/Iron Ball anulam isso.",
	"libero": "O tipo deste Pokémon muda de acordo com o tipo de golpe que ele está usando. Uma vez por troca.",
	"lightmetal": "O peso deste Pokémon foi reduzido pela metade.",
	"lightningrod": "Este Pokémon atrai golpes elétricos para si para aumentar o Sp. Ataque por 1; Imunidade elétrica.",
	"limber": "Este Pokémon não pode ser com Paralysis. Ganhar esta habilidade enquanto está com Paralysis a cura.",
	"lingeringaroma": "Fazer contato com este Pokémon faz com que a habilidade do atacante se torne Lingering Aroma.",
	"liquidooze": "Este Pokémon causa dano àqueles que drenam HP dele tanto quanto eles poderiam curar.",
	"liquidvoice": "Os golpes baseados em som deste Pokémon tornam-se do tipo Water.",
	"longreach": "Os ataques deste Pokémon não fazem contato com o alvo.",
	"magicbounce": "Este Pokémon bloqueia certos golpes da categoria Status e os devolve ao usuário.",
	"magicguard": "Este Pokémon só pode ser danificado por ataques diretos.",
	"magician": "Se este Pokémon não tiver nenhum item, ele rouba o item de um Pokémon que atingir com um ataque.",
	"magmaarmor": "Este Pokémon não pode ser com Freeze. Ganhar esta habilidade enquanto estiver com Freeze a cura.",
	"magnetpull": "Impede que Pokémon Steel-type adversários optem por trocar.",
	"marvelscale": "Se este Pokémon tiver uma condição de status não volátil, sua Defense será multiplicada por 1,5.",
	"megalauncher": "Os golpes de pulso deste Pokémon têm potência de 1,5x. Heal Pulse cura 3/4 do HP máximo do alvo.",
	"merciless": "Os ataques deste Pokémon são críticos se o alvo estiver com Poison.",
	"mimicry": "Os tipos deste Pokémon mudam para corresponder ao terreno. O tipo é revertido quando o terreno termina.",
	"mindseye": "Lutando, golpes normais atingem o Ghost. A Accuracy não pode ser reduzida, ignora a evasão.",
	"minus": "Se um aliado ativo tiver esta habilidade ou a habilidade Plus, o Sp. deste Pokémon. Atk é 1,5x.",
	"mirrorarmor": "Se os estágios de atributos deste Pokémon forem reduzidos, os do atacante serão reduzidos.",
	"mistysurge": "Ao entrar em campo, este Pokémon invoca Misty Terrain.",
	"moldbreaker": "Os golpes e efeitos deste Pokémon ignoram as habilidades de outros Pokémon.",
	"moody": "Aumenta uma estatística aleatória (exceto Accuracy/evasão) +2 e outra estatística -1 a cada turno.",
	"motordrive": "A Speed deste Pokémon aumenta 1 estágio se for atingido por um golpe elétrico; Imunidade elétrica.",
	"moxie": "O ataque deste Pokémon aumenta em 1 estágio se ele atacar e fazer desmaiar outro Pokémon.",
	"multiscale": "Se este Pokémon estiver com HP máximo, o dano recebido pelos ataques será reduzido pela metade.",
	"multitype": "Se este Pokémon for um Arceus, seu tipo muda para corresponder ao Plate segurado.",
	"mummy": "Pokémon que fazem contato com este Pokémon têm sua habilidade alterada para Múmia.",
	"myceliummight": "Os golpes da categoria Status deste Pokémon ficam em último lugar em sua faixa de prioridade e ignoram as habilidades.",
	"naturalcure": "Este Pokémon tem sua condição de status não volátil curada quando é desligado.",
	"neuroforce": "Os ataques deste Pokémon que são super effective contra o alvo causam 1,25x de dano.",
	"neutralizinggas": "Enquanto este Pokémon estiver ativo, as Habilidades não terão efeito.",
	"noguard": "Cada golpe usado por ou contra este Pokémon sempre acertará.",
	"normalize": "Os golpes deste Pokémon foram alterados para o tipo Normal e têm poder de 1,2x.",
	"oblivious": "Este Pokémon não pode ser apaixonado ou provocado. Imune à intimidação.",
	"opportunist": "Quando um Pokémon oponente tem um estágio de atributo aumentado, este Pokémon copia o efeito.",
	"orichalcumpulse": "Ao entrar em campo, invoca Sunny Day. Durante o dia ensolarado, o ataque é 1,3333x.",
	"overcoat": "Este Pokémon é imune a golpes de pólvora, dano de tempestade de areia e efeito Spore.",
	"overgrow": "Com 1/3 ou menos de seu HP máximo, a estatística ofensiva deste Pokémon é 1,5x com ataques de grama.",
	"owntempo": "Este Pokémon não pode ser confundido. Imune à intimidação.",
	"parentalbond": "Os golpes prejudiciais deste Pokémon acertam duas vezes. O segundo golpe tem seu dano reduzido.",
	"pastelveil": "Este Pokémon e seus aliados não podem ser com Poisons. Ao entrar em campo, cura aliados com Poisons.",
	"perishbody": "Fazer contato com este Pokémon inicia o efeito Perish Song para ele e para o atacante.",
	"pickpocket": "Se este Pokémon não tiver nenhum item e for atingido por um golpe de contato, ele rouba o item do atacante.",
	"pickup": "Se este Pokémon não tiver nenhum item, ele encontrará um usado por um Pokémon adjacente neste turno.",
	"pixilate": "Os golpes do tipo Normal deste Pokémon tornam-se do tipo Fairy e têm poder de 1,2x.",
	"plus": "Se um aliado ativo tiver esta habilidade ou a habilidade negativa, o Sp. deste Pokémon. Atk é 1,5x.",
	"poisonheal": "Este Pokémon é curado em 1/8 de seu HP máximo a cada turno quando com Poison; sem perda de HP.",
	"poisonpoint": "30% de chance de um Pokémon que fizer contato com este Pokémon ser com Poison.",
	"poisonpuppeteer": "Pecharunt: Se este Pokémon envenenar um alvo, o alvo também ficará confuso.",
	"poisontouch": "Os golpes de contato deste Pokémon têm 30% de chance de envenenamento.",
	"powerconstruct": "Se Zygarde estiver 10%/50%, muda para Completo se estiver com 1/2 do HP máximo ou menos no final do turno.",
	"powerofalchemy": "Este Pokémon copia a habilidade de um aliado que desmaia.",
	"powerspot": "Os aliados deste Pokémon têm o poder de seus golpes multiplicado por 1,3.",
	"prankster": "Os golpes da categoria Status deste Pokémon têm prioridade aumentada em 1, mas os tipos Dark são imunes.",
	"pressure": "Se este Pokémon for alvo de um golpe oponente, esse golpe perde um PP adicional.",
	"primordialsea": "Ao entrar em campo, chuva forte começa até que esta habilidade não esteja ativa na batalha.",
	"prismarmor": "Este Pokémon recebe 3/4 do dano de ataques super effective.",
	"propellertail": "Os golpes deste Pokémon não podem ser redirecionados para um alvo diferente por nenhum efeito.",
	"protean": "O tipo deste Pokémon muda de acordo com o tipo de golpe que ele está usando. Uma vez por troca.",
	"protosynthesis": "Sunny Day ativo ou Booster Energy usado: a estatística mais alta é 1,3x ou 1,5x se for Speed.",
	"psychicsurge": "Ao entrar em campo, este Pokémon invoca Psychic Terrain.",
	"punkrock": "Este Pokémon recebe 1/2 do dano de golpes Sleepros. Os seus próprios têm potência de 1,3x.",
	"purepower": "O ataque deste Pokémon é duplicado.",
	"purifyingsalt": "O dano fantasma a este Pokémon foi causado com uma estatística ofensiva reduzida pela metade; não pode ser status.",
	"quarkdrive": "Electric Terrain ativo ou Booster Energy usado: o atributo mais alto é 1,3x, ou 1,5x se for Speed.",
	"queenlymajesty": "Este Pokémon e seus aliados estão protegidos de golpes com prioridade adversários.",
	"quickdraw": "Este Pokémon tem 30% de chance de se mover primeiro em sua faixa de prioridade com golpes de ataque.",
	"quickfeet": "Se este Pokémon estiver com status, sua Speed é 1,5x; ignora a queda de Speed devido à Paralysis.",
	"raindish": "Se Rain Dance estiver ativo, este Pokémon cura 1/16 de seu HP máximo a cada turno.",
	"rattled": "A Speed aumenta 1 estágio se for atingido por um ataque do tipo Bug, Dark ou Ghost, ou Intimidado.",
	"receiver": "Este Pokémon copia a habilidade de um aliado que desmaia.",
	"reckless": "Os ataques deste Pokémon com recuo ou dano de colisão têm 1,2x de poder; não luta.",
	"refrigerate": "Os golpes do tipo Normal deste Pokémon tornam-se do tipo Ice e têm 1,2x de poder.",
	"regenerator": "Este Pokémon restaura 1/3 do seu HP máximo, arredondado para baixo, quando sai de campo.",
	"ripen": "Quando este Pokémon come certas frutas, os efeitos são duplicados.",
	"rivalry": "Os ataques deste Pokémon atingem 1,25x alvos do mesmo sexo; 0,75x no sexo oposto.",
	"rkssystem": "Se este Pokémon for um Silvally, seu tipo muda para corresponder à memória mantida.",
	"rockhead": "Este Pokémon não sofre dano de recuo além do dano de Luta/Life Orb/crash.",
	"rockypayload": "A estatística ofensiva deste Pokémon é multiplicada por 1,5 ao usar um ataque do tipo Rock.",
	"roughskin": "Pokémon que fazem contato com este Pokémon perdem 1/8 de seu HP máximo.",
	"runaway": "Não produz efeito durante a batalha.",
	"sandforce": "Os ataques Ground/Rock/Steel deste Pokémon causam 1,3x em Sandstorm; imunidade a isso.",
	"sandrush": "Se Sandstorm estiver ativo, a Speed deste Pokémon será duplicada; imunidade à Tempestade de Areia.",
	"sandspit": "Quando este Pokémon é atingido por um ataque, o efeito da Tempestade de Areia começa.",
	"sandstream": "Ao entrar em campo, este Pokémon invoca Sandstorm.",
	"sandveil": "Se Sandstorm estiver ativo, a evasão deste Pokémon é de 1,25x; imunidade à Tempestade de Areia.",
	"sapsipper": "O ataque deste Pokémon aumenta 1 estágio se for atingido por um golpe Grass; Imunidade à grama.",
	"schooling": "Se o usuário for Wishiwashi, muda para School Form se tiver> 1/4 do HP máximo, caso contrário, Solo Form.",
	"scrappy": "Lutando, golpes normais atingem o Ghost. Imune à intimidação.",
	"screencleaner": "Ao entrar em campo, os efeitos de Aurora Veil, Light Screen e Reflect terminam para ambos os lados.",
	"seedsower": "Quando este Pokémon é atingido por um ataque, o efeito de Grassy Terrain começa.",
	"serenegrace": "Os golpes deste Pokémon têm sua chance de efeito secundário duplicada.",
	"shadowshield": "Se este Pokémon estiver com HP máximo, o dano recebido pelos ataques será reduzido pela metade.",
	"shadowtag": "Impede que os oponentes optem por trocar, a menos que também tenham essa habilidade.",
	"sharpness": "Os golpes de corte deste Pokémon têm seu poder multiplicado por 1,5.",
	"shedskin": "Este Pokémon tem 33% de chance de ter seu status curado no final de cada turno.",
	"sheerforce": "Os ataques deste Pokémon com efeitos secundários têm 1,3x de poder; anula os efeitos.",
	"shellarmor": "Este Pokémon não pode ser atingido por um golpe crítico.",
	"shielddust": "Este Pokémon não é afetado pelo efeito secundário do ataque de outro Pokémon.",
	"shieldsdown": "Se for Minior, faça switch-in/final do turno e ele muda para Core com 1/2 HP máximo ou menos, caso contrário, Meteor.",
	"simple": "Quando um dos estágios de atributos deste Pokémon é aumentado ou diminuído, o valor é duplicado.",
	"skilllink": "Os ataques multi-hit deste Pokémon sempre atingem o número máximo de vezes.",
	"slowstart": "Ao entrar em campo, o Ataque e a Speed deste Pokémon são reduzidos pela metade por 5 turnos.",
	"slushrush": "Se Snow estiver ativo, a Speed deste Pokémon será duplicada.",
	"sniper": "Se este Pokémon acertar um golpe crítico, o dano será multiplicado por 1,5.",
	"snowcloak": "Se Snow estiver ativo, a evasão deste Pokémon é de 1,25x.",
	"snowwarning": "Ao entrar em campo, este Pokémon invoca Snow.",
	"solarpower": "Se Sunny Day estiver ativo, o Sp. O ataque é 1,5x; perde 1/8 do HP máximo por turno.",
	"solidrock": "Este Pokémon recebe 3/4 do dano de ataques super effective.",
	"soulheart": "O Sp. Attack deste Pokémon aumenta em 1 estágio quando outro Pokémon desmaia.",
	"soundproof": "Este Pokémon é imune a golpes baseados em som, a menos que tenha usado o golpe.",
	"speedboost": "A Speed deste Pokémon aumenta 1 estágio no final de cada turno completo no campo.",
	"stakeout": "A estatística ofensiva deste Pokémon é duplicada contra um alvo que trocou neste turno.",
	"stall": "Este Pokémon se move por último entre os Pokémon que usam golpes de prioridade igual ou superior.",
	"stalwart": "Os golpes deste Pokémon não podem ser redirecionados para um alvo diferente por nenhum efeito.",
	"stamina": "A defesa deste Pokémon aumenta em 1 estágio após ele ser danificado por um golpe.",
	"stancechange": "Se for Aegislash, muda Forme para Blade antes dos ataques e Shield antes de King's Shield.",
	"static": "30% de chance de um Pokémon que fizer contato com este Pokémon ficar com Paralysis.",
	"steadfast": "Se este Pokémon recuar, sua Speed aumentará em 1 estágio.",
	"steamengine": "A Speed deste Pokémon aumenta em 6 estágios após ser danificado por golpes de Fogo/Água.",
	"steelworker": "A estatística ofensiva deste Pokémon é multiplicada por 1,5 ao usar um ataque do tipo Steel.",
	"steelyspirit": "Este Pokémon e os golpes do tipo Steel de seus aliados têm seu poder multiplicado por 1,5.",
	"stench": "Os ataques deste Pokémon sem chance de vacilar ganham 10% de chance de vacilar.",
	"stickyhold": "Este Pokémon não pode perder seu item devido à habilidade ou ataque de outro Pokémon.",
	"stormdrain": "Este Pokémon atrai golpes de água para si mesmo para aumentar o Sp. Ataque por 1; Imunidade à água.",
	"strongjaw": "Os ataques baseados em mordidas deste Pokémon têm poder de 1,5x. Bug Bite não é aumentado.",
	"sturdy": "Se este Pokémon estiver com HP máximo, ele sobreviverá a um golpe com pelo menos 1 HP. Imune a OHKO.",
	"suctioncups": "Este Pokémon não pode ser forçado a trocar por ataque ou item de outro Pokémon.",
	"superluck": "A taxa de acerto crítico deste Pokémon é aumentada em 1 estágio.",
	"supersweetsyrup": "Ao entrar em campo, este Pokémon reduz a evasão dos oponentes em 1 estágio. Uma vez por batalha.",
	"supremeoverlord": "Os golpes deste Pokémon têm 10% mais poder para cada aliado desmaiado, até 5 aliados.",
	"surgesurfer": "Se Electric Terrain estiver ativo, a Speed deste Pokémon será duplicada.",
	"swarm": "Com 1/3 ou menos de seu HP máximo, a estatística ofensiva deste Pokémon é 1,5x com ataques de Bug.",
	"sweetveil": "Este Pokémon e seus aliados não conseguem dormir; quem já está dormindo não acorda.",
	"swiftswim": "Se Rain Dance estiver ativo, a Speed deste Pokémon será duplicada.",
	"swordofruin": "Pokémon ativos sem esta habilidade têm sua defesa multiplicada por 0,75.",
	"symbiosis": "Se um aliado usar seu item, este Pokémon entrega seu item a esse aliado imediatamente.",
	"synchronize": "Se outro Pokémon queimar/envenenar/paralisar este Pokémon, ele também receberá esse status.",
	"tabletsofruin": "Pokémon ativos sem esta habilidade têm seu ataque multiplicado por 0,75.",
	"tangledfeet": "A evasão deste Pokémon é duplicada enquanto ele estiver confuso.",
	"tanglinghair": "Pokémon que fazem contato com este Pokémon têm sua Speed reduzida em 1 estágio.",
	"technician": "Os golpes deste Pokémon de 60 de poder ou menos têm 1,5x de poder, incluindo Struggle.",
	"telepathy": "Este Pokémon não sofre danos de ataques de seus aliados.",
	"teraformzero": "Terápagos: Terastalização acaba com os efeitos do clima e do terreno. Uma vez por batalha.",
	"terashell": "Terápagos: Se estiver com HP cheio, os ataques realizados têm 0,5x de eficácia, a menos que estejam naturalmente imunes.",
	"terashift": "Se este Pokémon for um Terapagos, ele se transforma em sua Forma Terastal ao entrar.",
	"teravolt": "Os golpes e efeitos deste Pokémon ignoram as habilidades de outros Pokémon.",
	"thermalexchange": "O ataque deste Pokémon aumenta em 1 quando danificado por golpes Fire; não pode receber Burn.",
	"thickfat": "Golpes do tipo Fire/Gelo contra este Pokémon causam dano com uma estatística ofensiva reduzida pela metade.",
	"tintedlens": "Os ataques deste Pokémon que não são muito eficazes em um alvo causam dano duplo.",
	"torrent": "Com 1/3 ou menos de seu HP máximo, a estatística ofensiva deste Pokémon é 1,5x com ataques de Água.",
	"toughclaws": "Os golpes de contato deste Pokémon têm seu poder multiplicado por 1,3.",
	"toxicboost": "Embora este Pokémon esteja com Poison, seus ataques físicos têm 1,5x de poder.",
	"toxicchain": "Os ataques deste Pokémon têm 30% de chance de envenenamento grave.",
	"toxicdebris": "Se este Pokémon for atingido por um ataque físico, Toxic Spikes serão colocados no lado oposto.",
	"trace": "Ao entrar em campo, ou quando possível, este Pokémon copia a Ability de um oponente adjacente aleatório.",
	"transistor": "A estatística ofensiva deste Pokémon é multiplicada por 1,3 ao usar um ataque do tipo Electric.",
	"triage": "Os golpes de cura deste Pokémon têm sua prioridade aumentada em 3.",
	"truant": "Este Pokémon pula turnos alternados em vez de usar um golpe.",
	"turboblaze": "Os golpes e efeitos deste Pokémon ignoram as habilidades de outros Pokémon.",
	"unaware": "Este Pokémon ignora os estágios de atributos de outros Pokémon ao receber ou causar dano.",
	"unburden": "A Speed é duplicada na perda de itens equipados; o impulso é perdido se ele mudar e receber um novo item/habilidade.",
	"unnerve": "Enquanto este Pokémon estiver ativo, ele evita que Pokémon adversários usem suas Berries.",
	"unseenfist": "Os golpes de contato deste Pokémon ignoram a proteção do alvo, exceto Max Guard.",
	"vesselofruin": "Pokémon ativos sem esta habilidade têm seu Sp. Attack multiplicado por 0,75.",
	"victorystar": "Os golpes deste Pokémon e de seus aliados têm sua Accuracy multiplicada por 1,1.",
	"vitalspirit": "Este Pokémon não consegue dormir. Ganhar esta habilidade enquanto dorme cura-a.",
	"voltabsorb": "Este Pokémon cura 1/4 do seu HP máximo quando atingido por golpes elétricos; Imunidade elétrica.",
	"wanderingspirit": "Pokémon que fazem contato com este Pokémon têm sua habilidade trocada por esta.",
	"waterabsorb": "Este Pokémon cura 1/4 de seu HP máximo quando atingido por golpes de Água; Imunidade à água.",
	"waterbubble": "O poder de água deste Pokémon é 2x; não pode receber Burn; O poder de fogo contra ele é reduzido pela metade.",
	"watercompaction": "A defesa deste Pokémon aumenta 2 estágios após ser danificado por um golpe do tipo Water.",
	"waterveil": "Este Pokémon não pode receber Burn. Ganhar esta habilidade enquanto estiver com Burn a cura.",
	"weakarmor": "Se um ataque físico atingir este Pokémon, a Defense será reduzida em 1 e a Speed aumentada em 2.",
	"wellbakedbody": "A defesa deste Pokémon aumenta 2 estágios se for atingido por um golpe de Fogo; Imunidade a Fire.",
	"whitesmoke": "Impede que outros Pokémon reduzam os estágios de atributos deste Pokémon.",
	"wimpout": "Este Pokémon troca quando atinge 1/2 ou menos do seu HP máximo.",
	"windpower": "Este Pokémon ganha o efeito Charge quando é atingido por um golpe de vento ou quando o Tailwind começa.",
	"windrider": "Attack aumentado em 1 se for atingido por um golpe de vento ou Vento de cauda começar. Imunidade ao golpe do vento.",
	"wonderguard": "Este Pokémon só pode ser danificado por golpes super effective e danos indiretos.",
	"wonderskin": "Golpes de status com verificações de Accuracy são 50% precisos quando usados neste Pokémon.",
	"zenmode": "Se for Darmanitan, no final do turno muda o Modo para Padrão se > 1/2 HP máximo, caso contrário, Zen.",
	"zerotohero": "Se este Pokémon for um Palafin em Zero Form, a troca faz com que ele mude para Hero Form."
};

export function getRPGAbilityDescriptionPTBR(abilityId: string): string {
	return ABILITY_DESCRIPTIONS_PT_BR[abilityId] || GENERATED_ABILITY_DESCRIPTIONS_PT_BR[abilityId] ||
		'A descrição desta habilidade ainda não está disponível em português.';
}